[tool.poetry]
name = "metaculus-web"
version = "0.1.0"
description = ""
authors = ["George3d6 <george@cerebralab.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"
django = "^5.0.6"
djangorestframework = "^3.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
